### ISSUE TITLE
How to read / write data to the expression-session

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [adamelliotfields/express-session-example#2]
Hi @adamelliotfields ,thank you for publishing your example.

I amworking with node/typescript and express

I looked up desperately google and github, to find a way to read/write data to my httpsession (I amusing package `express-session`, klike you and many) : 
* when I `console.log(req.session)`, I see data like : 

```bash 
---------------------------------------
 Express Session is : 
Session {
  cookie: { path: '/', _expires: null, originalMaxAge: null, httpOnly: true },
  passport: {
    user: {
      github_profile: [Object],
      some_custom_property_i_just_added_myself: '65464546454sdf'
    }
  }
}
---------------------------------------

```
* and in typescript, If  I try to `req.session.passport` or `req.session["passport"]`,then my compiler of course gives me an error...
* How can I access those properties which **I know** are there, really could not find one example anywhere... Was hoping with your nice work here, but unfortunately, I cannot see anywhere in your source code any access to session data...

Would you have any tip on how to do that ..?

**Comment by Jean-Baptiste-Lasselle** [comment]
sorry for the disturbance, I found a workaround, thank you anyway for your source code

**Comment by adamelliotfields** [comment]
No problem, Jean-Baptiste. Feel free to reach out if you need any additional assistance.
